# Schema
schema_version: 1.0.0
schema_type: mlcube_task

# Task Inputs
inputs:
        - name: flagfile
          type: file
# Task Outputs
outputs:
        - name: log_dir
          type: directory
        - name: data_dir
          type: directory
