name: Linting

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.10
    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.16.1
    - name: Run pylint
      run: |
        pylint algorithmic_efficiency
        pylint reference_algorithms
        pylint prize_qualification_baselines
        pylint submission_runner.py
        pylint tests

  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.10
    - name: Install isort
      run: |
        python -m pip install --upgrade pip
        pip install isort
    - name: Run isort
      run: |
        isort . --check --diff

  yapf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.10
    - name: Install yapf
      run: |
        python -m pip install --upgrade pip
        pip install yapf==0.32
    - name: Run yapf
      run: |
        yapf . --diff --recursive
