name: Run submission

on: 
  pull_request:
    branches:
      - 'scoring' 
env:
  SUBMISSION_PATH: /algorithmic-efficiency/submissions/submissions_algorithms_v0_5/AlgoPerf_Team_11/external_tuning/nadamp/submission.py
  TUNING_SEARCH_SPACE_FLAG: /algorithmic-efficiency/submissions/submissions_algorithms_v0_5/AlgoPerf_Team_11/external_tuning/nadamp/tuning_search_space.json
  EXPERIMENT_NAME: ch/Team_11/external_tuning/nadamp
  FRAMEWORK: jax
  DOCKER_IMAGE: us-central1-docker.pkg.dev/training-algorithms-external/mlcommons-docker-repo/algoperf_jax_main_scoring
  HELDOUT_WORKLOADS_PATH: /algorithmic-efficiency/scoring/held_out_workloads.json
  WORKLOAD_METADATA_PATH: /algorithmic-efficiency/workload_metadata_external_tuning.json
jobs:
  run_workloads:
    strategy:
      matrix:
        study: [0, 1, 2, 3, 4]
        trial: [0, 1, 2, 3, 4]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run containerized workload
      run: |
        docker pull $DOCKER_IMAGE
        export TRIAL_INDEX=${{ matrix.trial }}
        echo $TRIAL_INDEX
        python /home/kasimbeg/algorithmic-efficiency/scoring/run_workloads.py \
        --framework $FRAMEWORK \
        --local False \
        --experiment_name $EXPERIMENT_NAME \
        --docker_image_url $DOCKER_IMAGE \
        --run_percentage 100 \
        --submission_path $SUBMISSION_PATH \
        --tuning_search_space $TUNING_SEARCH_SPACE \
        --held_out_workloads_config_path $HELDOUT_WORKLOADS_PATH \
        --study_start_index ${{ matrix.study }} \
        --study_end_index ${{ matrix.study }} \
        --hparam_start_index ${{ matrix.trial }} \
        --hparam_end_index $(( ${{ matrix.trial }} + 1 )) \
        --workload_metadata_path $WORKLOAD_METADATA \
        --seed 0 \
        --dry_run True