name: Run submission

on: 
  pull_request:
    branches:
      - 'scoring' 
env:
  SUBMISSION_PATH: /home/kasimbeg/algorithmic-efficiency/some_path
  TUNING_SEARCH_SPACE_FLAG: /home/kasimbeg/algorithmic-efficiency/some_path
  EXPERIMENT_NAME: Team_blub/some_submission_path
  FRAMEWORK: jax
  DOCKER_IMAGE: us-central1-docker.pkg.dev/training-algorithms-external/mlcommons-docker-repo/algoperf_jax_dev
  HELDOUT_WORKLOADS_PATH: /home/kasimbeg/algorithmic-efficiency/some_path
jobs:
  run_workloads:
    strategy:
      matrix:
        study: [0, 1, 2, 3, 4]
        trial: [0, 1, 2, 3, 4]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run containerized workload
      run: |
        docker pull $DOCKER_IMAGE
        python run_workloads.py --framework $FRAMEWORK \
        --local False \
        --experiment_name $EXPERIMENT_NAME \
        --docker_image_url us-central1-docker.pkg.dev/training-algorithms-external/mlcommons-docker-repo/algoperf_jax_dev \
        --run_percentage 100 \
        --submission_path $SUBMISSION_PATH \
        --tuning_search_space $TUNING_SEARCH_SPACE \
        --held_out_workloads_config_path $HELDOUT_WORKLOADS_PATH \
        --study_start_index {{ matrix.study }} \
        --study_end_index {{ matrix.study }} \
        --hparam_start_index {{ matrix.trial }} \
        --hparam_end_index $(( {{ matrix.trial }} + 1 )) \
        --workload_metadata_path workload_metadata_external_tuning.json \
        --seed 0 \
        --dry_run True